<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
    <PackageReference Include="Monocle" Version="0.9.4.5" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FNA\FNA.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Celeste">
      <HintPath>$(CelesteDirectory)\Celeste.exe</HintPath>
    </Reference>
  </ItemGroup>

    <!-- Copy our compiled DLL to Celeste after every successful build -->
    <Target Name="CopyToCeleste" AfterTargets="Build">

	    <Copy
		    SourceFiles="$(TargetPath)"
		    DestinationFolder="$(CelesteDirectory)"
		    SkipUnchangedFiles="true" />

    </Target>

</Project>
